#global
seed: 42
log_path: './logs/'

# data
data_name: 
data_path: './dataset/METR/Flow.npy'
adj_path: './dataset/METR/dists.npy'
order_of_cheb: 3
windows: 12
lag: 0
horizon: 12
train_ratio: 0.6
val_ratio: 0.1
bs: 32
is_scaler: True

# model
model_name: 'STGCN'
ks: 3
kt: 3
lr: 0.001
blocks: [[1, 32, 64], [64, 32, 128]]
droprate: 0
epochs: 500
patience: 32
is_collected: False
