#global
seed: 42
log_path: './logs/'

# data
data_name: 
data_path: './dataset/METR/Flow.npy'
adj_path: './dataset/METR/dists.npy'
windows: 12
lag: 0
horizon: 12
train_ratio: 0.6
val_ratio: 0.1
bs: 32
is_scaler: True
load_adj: False
is_collected: False

# model
model_name: 'AGCRN'
order_of_cheb: 2
d_in: 1
d_out: 1
d_em: 2
units: 16
layers: 2
lr: 0.001
droprate: 0
epochs: 500
patience: 32
